# Generated by Django 5.1.3 on 2024-11-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
