# Generated by Django 5.1.3 on 2024-11-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myweb', '0002_delete_project_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='images/')),
                ('urls', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=40)),
                ('author_position', models.CharField(max_length=20)),
                ('comments', models.TextField()),
                ('profile_img', models.ImageField(upload_to='images/author/')),
            ],
        ),
    ]
