# Generated by Django 5.1 on 2024-11-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonies',
            new_name='Testimonie',
        ),
    ]
